# Generated by Django 5.1.4 on 2024-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'verbose_name': 'Robot', 'verbose_name_plural': 'Robots'},
        ),
        migrations.AddField(
            model_name='robot',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
